# Generated by Django 3.2.4 on 2021-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Welcome! click the link above to read the blog', max_length=100),
        ),
    ]
