# Generated by Django 3.2.4 on 2021-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0011_auto_20210702_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
